### ISSUE TITLE
php cour 11_09_2019 cahier des charge non respecter 

### ISSUE THREAD

**Issue by DamienSasso** [wezerg/Php_double_boucle_rand01#1]
Bonjour le cahier des charge indiquait que lorsqu'un nombre est présent plus de deux fois celui ci devait s'afficher en rouge hors se n'est pas le cas pourriez vous adapter votre code pour répondre à cela je vous prit.

**Comment by wezerg** [comment]
Je vais effectuer la correction dès maintenant.
